### ISSUE TITLE
How is R0 defined in terms of the states? (Scenario 2)

### ISSUE THREAD

**Issue by ChrisRackauckas** [ChrisRackauckas/ASKEM_Evaluation_Staging#20]

**Comment by YingboMa** [comment]
@liunelson How can we get:

> D the mean duration of infectiousness

**Comment by liunelson** [comment]
@YingboMa 
The SIDARTHE-V paper actually defines it right after Fig. 2:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8205853/

>the effective reproduction number Reff(t) = R0 * S(t) goes below 1 due to the decreasing susceptible fraction S(t); hence, the epidemic is eventually suppressed

R0 is defined in the methods section:
>parametric reproduction number R0 is the H∞ norm of the positive system from u to ys with parameters tuned at the beginning of the epidemic...

**Comment by Free-Quarks** [comment]
https://drive.google.com/file/d/1es3vJlB3ExvOmigpVG3-Op1TeCDUwgyP/view?usp=share_link

**Comment by Free-Quarks** [comment]
that screen shot is from this paper: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7175834/pdf/41591_2020_Article_883.pdf

**Comment by liunelson** [comment]
@YingboMa 
Please clarify what R0 and Reff(t) definition you are using.
Based on the SIDARTHE-V, R0 = beta/gamma and Reff(t) = R0 * S(t) where R0 = lim(t -> 0) Reff(t).
Your earlier notebook used some random D value?

**Comment by YingboMa** [comment]
R0 is defined as this https://github.com/ChrisRackauckas/ASKEM_Evaluation_Staging/pull/57#issue-1565304425

And `R_t = R0 * S`

**Comment by YingboMa** [comment]
I haven't updated the notebook yet because the updated question from MITRE is still ill-formed.
