### ISSUE TITLE
Usability & Help a new Programmer to get started

### ISSUE THREAD

**Issue by kellertuer** [ChrisRackauckas/ASKEM_Evaluation_Staging#62]
When one want to reproduce the scenarios from here it would be nice to have an easy entry level.

As soon as I saw that the scenarios are in the docs and how to run them is described at
https://chrisrackauckas.github.io/ASKEM_Evaluation_Staging/dev/

I could run this easily. But finding that took a few minutes. Maybe one could make the link in the readme more prominent – i.e. also mentioning that the link includes a manual on how to run the scenarios or one could include the part of the docs mentioning how to run this also in the readme.
This could for example be the part with 

-----

To run locally, start by downloading this Github repository. Then open Julia and run:

```
cd("to the ASKEM_Evaluation_Staging/docs directory")

# Setup packages
using Pkg
Pkg.activate(".") 
Pkg.instantiate()

# Run the build script
include("make.jl")
```

----

(or one could even ask the user to first navigate to the docs folder and start Julia there).

**Comment by ChrisRackauckas** [comment]
<img width="681" alt="Screenshot 2023-02-01 094926" src="https://user-images.githubusercontent.com/1814174/216075828-e7e7289b-1300-483f-bc3d-9bf73820fc33.png">

**Comment by ChrisRackauckas** [comment]
Thanks for giving it a try! I just pushed some improvements to main.

Could you estimate the amount of time it took for you to get things running?

**Comment by kellertuer** [comment]
My main confusion was that I did not expect the scenarios in the `docs/` environment – so I was looking for that about 10 minutes maybe.

Without that time, now that the docs folder and even the code to start is given in the Readme, these 10 minutes are not required and the rest was about 4-5 minutes.
