### ISSUE TITLE
Scenario 2 Question 1.c

### ISSUE THREAD

**Issue by liunelson** [ChrisRackauckas/ASKEM_Evaluation_Staging#68]
@YingboMa 
Please customized the total order indices plot as follows:
* drop the first/second order indices
* rotate the x-axis label 45 or 90 degrees for legibility
* yscale = log10 so that we can actually see tau's value
* sorting along the x-axis in decreasing order would be helpful

Note that if you had used the SIDARTHE model from TA2 MIRA, there wouldn't be the dummy `Italy` parameter.
https://github.com/DARPA-ASKEM/program-milestones/tree/main/6-month-milestone/evaluation/scenario_2/ta_2

**Comment by YingboMa** [comment]
> Note that if you had used the SIDARTHE model from TA2 MIRA, there wouldn't be the dummy Italy parameter.

Yes, @JeffBezanson is working on that in #60

**Comment by YingboMa** [comment]
> yscale = log10 so that we can actually see tau's value

Sensitivity is actually directional, so some are negative and some are zero, so log scale won't make sense.
