### ISSUE TITLE
Scenario 2 Question 2.b

### ISSUE THREAD

**Issue by liunelson** [ChrisRackauckas/ASKEM_Evaluation_Staging#69]
@YingboMa 
The TA2 MMT and Petri net representation of SIDARTHE-V is here:
https://github.com/DARPA-ASKEM/experiments/tree/main/thin-thread-examples/milestone_6month/evaluation/indra/scenario_2/sidarthe-v

**Comment by YingboMa** [comment]
The model isn't written by me. @JeffBezanson is working on the integration.
